////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 14.0Release
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class BatteryMesg extends Mesg {

   protected static final	Mesg batteryMesg;
   static {
      // battery
      batteryMesg = new Mesg("battery", MesgNum.BATTERY);
      //batteryMesg.addField(new Field("unkown1", 0, 132, 1, 0, "", false));
      //batteryMesg.addField(new Field("unkown2", 1, 2, 1, 0, "", false));
      batteryMesg.addField(new Field("level", 2, 2, 1, 0, "", false));
      //batteryMesg.addField(new Field("unkown3", 3, 2, 1, 0, "", false));
      //batteryMesg.addField(new Field("unkown4", 253, 133, 1, 0, "", false));
   }

   public BatteryMesg() {
      super(Factory.createMesg(MesgNum.BATTERY));
   }

   public BatteryMesg(final Mesg mesg) {
      super(mesg);
   }

   public Short getLevel() {
       return getFieldShortValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

}
